language: java
jdk:
  - openjdk11

#branches:
#  only:
#    - main

    # travis CI 서버 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
  - chmod +x scripts/deploy.sh

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - chmod +x build/libs/*.jar
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy ./*
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/springboot-blog.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: blog-build-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: blog-build-bucket
    key: springboot-blog.zip
    bundle_type: zip
    application: springboot-blog
    deployment_group: springboot-blog-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - creee77@gmail.com

